### ISSUE TITLE
X10 CM11A

### ISSUE THREAD

**Issue by jcoudrais** [mika-nt28/Jeedom-mochad#10]
Hi, quite a good news to get X10 on jeedom ! Good job.
Do you think CM11A should work, driver is ok
[99305.712243] pl2303 1-1.5:1.0: pl2303 converter detected
[99305.716662] usb 1-1.5: pl2303 converter now attached to ttyUSB0

I got this error 
 libusb_open_device_with_vid_pid failed
mochad[29859]: Could not find/open CM15A/CM19A -5

I got it working on my old NAS with that rule
SUBSYSTEMS=="usb", SYSFS{idVendor}=="067b", KERNEL=="ttyUSB*", SYMLINK+="cm11a", MODE="0666"

Should it help...

**Comment by mika-nt28** [comment]
This problem is a Mochad project (http://downloads.sourceforge.net/project/mochad)
